Working on FGSM
	Working on U_lenet_w_acc_94
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
Testing on Rank 0
Testing on Rank 1
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
	Working on lenet_w_acc_98
Testing on Rank 0
Testing on Rank 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Run Complete
Working on PGD
	Working on U_lenet_w_acc_94
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
Testing on Rank 0
Testing on Rank 1
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
	Working on lenet_w_acc_98
Testing on Rank 1
Testing on Rank 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/util.py", line 110, in _remove_temp_dir
    rmtree(tempdir)
  File "/usr/lib/python3.8/shutil.py", line 719, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 717, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pymp-2wjseg67'
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
Working on CW2
	Working on U_lenet_w_acc_94
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
Testing on Rank 0
Testing on Rank 1
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
	Working on lenet_w_acc_98
Testing on Rank 0
Testing on Rank 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Run Complete
Working on OSSA
	Working on U_lenet_w_acc_94
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
Testing on Rank 0
Testing on Rank 1
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
	Working on lenet_w_acc_98
Testing on Rank 0
Testing on Rank 1
Evaluating Results 1
Val Gathered 1
Adv Gathered 1
Evaluating Results 0
Val Gathered 0
Adv Gathered 0
Saving Attack Results to Excel
Save Attack Results
Run Complete
Working on EoT
	Working on U_lenet_w_acc_94
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
models/pretrained/MNIST/U_w_means_0-10024631768465042_and_stds_0-9899614453315735_.pt  is Loaded.
Testing on Rank 0
Testing on Rank 1
Invalid Attack Type
None
Invalid Attack Type
None
Traceback (most recent call last):
  File "ddp_model_trainer.py", line 641, in <module>
    run_ddp(train, n_gpus, config, project_name)
  File "ddp_model_trainer.py", line 530, in run_ddp
    mp.spawn(func,
  File "/home/naddeok5/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/naddeok5/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/naddeok5/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 139, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
